name: donghaeng
description: 동행

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  provider: ^6.0.3
  json_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  json_serializable:
  build_runner:
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/