name: donghaeng
description: 기기

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.3.0"
dependencies:
  flutter:
    sdk: flutter
  # Resource
  cupertino_icons:
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.3
  flutter_svg_provider: ^1.0.3
  cached_network_image: ^3.2.1

  # Provider
  provider: ^6.0.3

  # Firebase
  google_sign_in: ^5.4.1
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.2
  flutterfire_ui: ^0.4.3+4
  firebase_database: ^9.1.0
  cloud_firestore: ^3.4.4
  firebase_storage: ^10.3.7

  # DI
  get_it: ^7.2.0

  # Util
  json_annotation:
  intl: ^0.17.0
  url_strategy: ^0.2.0
  flutter_dotenv: ^5.0.2
  tuple: ^2.0.0
  fluttertoast: ^8.0.9
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  json_serializable:
  build_runner:
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/
    - assets/icons/
    - env
  fonts:
    - family: Noto_Sans_KR
      fonts:
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Thin.otf
          weight: 100
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Light.otf
          weight: 300
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Regular.otf
          weight: 400
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Bold.otf
          weight: 700
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Black.otf
          weight: 900