name: donghaeng
description: 동행

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.5"
dependencies:
  flutter:
    sdk: flutter
  # Resource
  cupertino_icons:
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.3

  # Provider
  provider: ^6.0.3

  # Firebase
  google_sign_in: ^5.4.1
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.2
  flutterfire_ui: ^0.4.3+4
  firebase_database: ^9.1.2
  cloud_firestore: ^3.4.4

  # DI
  get_it: ^7.2.0

  # Util
  json_annotation:
  intl: ^0.17.0
  url_strategy: ^0.2.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  json_serializable:
  build_runner:
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/
    - assets/icons/
    - env